CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"

#nav
GRAPH_TOKEN = "<graph>"
GRAPH_TOKEN_INDEX = -300
NODE_BEGIIN_TOKEN = "<node>"
NODE_BEGIIN_TOKEN_INDEX = -301
NODE_END_TOKEN = "</node>"
NODE_END_TOKEN_INDEX = -302
STOP_TOKEN = "<stop>"
STOP_TOKEN_INDEX = -303
NAV_INSTR_BEGIN_TOKEN = "<nav>"
NAV_INSTR_END_TOKEN = "</nav>"
IDX_BEGIN_TOKEN = "<idx>"
IDX_END_TOKEN = "</idx>"